language: node_js

node_js:
  - '8'

branches:
  only:
  - master

install:
  - npm install -g travis-ci-cloudfront-invalidation
  - npm install

script
  - npm run build
  - cd dist/
  - ls -la

deploy:
  provider: s3
  skip_cleanup: true
  local_dir: dist
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  region: $AWS_REGION

after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
